name: Automated Code Quality Fixes and Copilot Review

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  detect-errors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run checks (TypeScript, ESLint, ShellCheck, etc.)
        run: |
          npm ci
          npx tsc --noEmit || echo "::set-output name=error::true"
          npx eslint . --ext .js,.ts || echo "::set-output name=error::true"
          # ... other checks ...
      - name: Gather and explain errors
        if: steps.checks.outputs.error == 'true'
        run: |
          echo "Detected issues. See report." > error_report.txt
          # Add explanations or diagnostics here

      - name: Create Pull Request for Fixes
        if: steps.checks.outputs.error == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Automated Code Quality Fixes"
          body: |
            This PR addresses code quality issues detected by the automated workflow.
            Copilot will be assigned for AI-powered review and fix suggestions.
          assignees: dzp5103
          labels: auto-fix, copilot-review

  copilot-review:
    needs: detect-errors
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copilot AI Review
        uses: github/copilot-actions/review@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
