name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
    
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    # Only run if WAKATIME_API_KEY is set
    if: ${{ secrets.WAKATIME_API_KEY != '' }}
    permissions:
      contents: write
      
    steps:
      # Checkout repository to access files
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Verify WAKATIME_API_KEY is available before proceeding
      - name: Verify WakaTime API Key
        run: |
          if [ -z "${{ secrets.WAKATIME_API_KEY }}" ]; then
            echo "::warning::WAKATIME_API_KEY secret is not set. Skipping WakaTime stats update."
            echo "To enable WakaTime integration, add your WakaTime API key as a repository secret named 'WAKATIME_API_KEY'."
            exit 0
          fi
          echo "WakaTime API key is available, proceeding with stats update."
          
      # Update README with WakaTime stats
      - name: Update README with WakaTime stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LANGUAGE: "True"
          SHOW_TIMEZONE: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_UPDATED_DATE: "False"
          LOCALE: "en"
        continue-on-error: true